DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE Individuals CASCADE CONSTRAINTS;
DROP TABLE Companies CASCADE CONSTRAINTS;
DROP TABLE Vehicles CASCADE CONSTRAINTS;
DROP TABLE Workplace CASCADE CONSTRAINTS;
DROP TABLE Employees CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Calendar_Items CASCADE CONSTRAINTS;
DROP TABLE Services CASCADE CONSTRAINTS;
DROP TABLE Store_Items CASCADE CONSTRAINTS;
DROP TABLE Technician CASCADE CONSTRAINTS;
DROP TABLE Mechanic CASCADE CONSTRAINTS;
DROP TABLE Manager CASCADE CONSTRAINTS;
DROP TABLE Training_Programs CASCADE CONSTRAINTS;

CREATE TABLE Customers (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL
);

CREATE TABLE Individuals (
    ID INT PRIMARY KEY REFERENCES Customers(ID),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE Companies (
    ID INT PRIMARY KEY REFERENCES Customers(ID),
    IC VARCHAR(10) UNIQUE NOT NULL CHECK (REGEXP_LIKE(IC,'[0-9]{8,10}')),
    DIC VARCHAR(12) UNIQUE NOT NULL CHECK (REGEXP_LIKE(DIC,'[A-Z]{2}[0-9]{8,10}'))
);

CREATE TABLE Vehicles (
    VIN VARCHAR(17) PRIMARY KEY,
    customer_ID NUMBER NOT NULL,
    FOREIGN KEY (customer_ID) REFERENCES Customers(ID),
    customer_tag VARCHAR(50)
);

CREATE TABLE Workplace (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ VARCHAR(100) NOT NULL --workplace_name
);

CREATE TABLE Employees (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    workplace_ID NUMBER,
    FOREIGN KEY (workplace_ID) REFERENCES Workplace(ID)
);

CREATE TABLE Orders (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_ VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    expected_finish_date DATE,
    price NUMERIC,
    billable_time INT, --sekundy
    description_ VARCHAR(500),
    vehicle_ID VARCHAR(17),
    customer_ID INT,
    technician_ID INT,
    FOREIGN KEY (vehicle_ID) REFERENCES Vehicles(VIN),
    FOREIGN KEY (customer_ID) REFERENCES Customers(ID),
    FOREIGN KEY (technician_ID) REFERENCES Employees(ID)
);

CREATE TABLE Calendar_Items (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ID INT,
    FOREIGN KEY (order_ID) REFERENCES Orders(ID),
    date_ DATE NOT NULL, --calendar_date
    start_time_ TIMESTAMP NOT NULL, --calendar_start
    end_time_ TIMESTAMP NOT NULL, --calendar_end
    is_assigned NUMBER(1) DEFAULT 0,
    type_ VARCHAR(50), --calendar_type
    created_by_ID INT,
    FOREIGN KEY (created_by_ID) REFERENCES Employees(ID),
    assigned_by_ID INT,
    --1) assigned_by_ID spravit (0,1) ale potom neobsahuje ID mozno takto
    --assigned_by_type INT CHECK (assigned_by_type IN (0,1)),
    --CHECK(
    --  (assigned_by_type = 0 AND assigned_by_ID IN (SELECT ID FROM Customers)) OR
    --  (assigned_by_type = 1 AND assigned_by_ID IN (SELECT ID FROM Employees))
    --)
    workplace_ID INT,
    mechanic_ID INT,
    FOREIGN KEY (workplace_ID) REFERENCES Workplace(ID),
    FOREIGN KEY (mechanic_ID) REFERENCES Employees(ID)
);

CREATE TABLE Services (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price NUMERIC NOT NULL,
    expected_time INT, --SEKUNDY
    needed_specialisation VARCHAR(50) NOT NULL,
    type_ INT CHECK (type_ IN (0,1)) --service_type
);

CREATE TABLE Store_Items (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_address VARCHAR(255) NOT NULL,
    name_ VARCHAR(100) NOT NULL, --item_name
    quantity INT NOT NULL,
    price NUMERIC NOT NULL
);


CREATE TABLE Technician (
    ID INT PRIMARY KEY REFERENCES Employees(ID),
    work_focus INT CHECK (work_focus IN (0,1))
);

CREATE TABLE Mechanic (
    ID INT PRIMARY KEY REFERENCES Employees(ID)
    -- mozne prepojenie mechanic->training_program?
    -- ze treningovy program bude mat <fk> id mechanika (cize employees) 
);

CREATE TABLE Manager (
    ID INT PRIMARY KEY REFERENCES Employees(ID)
);

CREATE TABLE Training_Programs (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- treba nejake inserty porobit

