DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE Individuals CASCADE CONSTRAINTS;
DROP TABLE Companies CASCADE CONSTRAINTS;
DROP TABLE Vehicles CASCADE CONSTRAINTS;
DROP TABLE Workplace CASCADE CONSTRAINTS;
DROP TABLE Employees CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Calendar_Items CASCADE CONSTRAINTS;
DROP TABLE Services CASCADE CONSTRAINTS;
DROP TABLE Store_Items CASCADE CONSTRAINTS;
DROP TABLE Technician CASCADE CONSTRAINTS;
DROP TABLE Mechanic CASCADE CONSTRAINTS;
DROP TABLE Manager CASCADE CONSTRAINTS;
DROP TABLE Training_Programs CASCADE CONSTRAINTS;


CREATE TABLE Customers (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL
);

CREATE TABLE Individuals (
    ID INT PRIMARY KEY REFERENCES Customers(ID),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE Companies (
    ID INT PRIMARY KEY REFERENCES Customers(ID),
    IC VARCHAR(10) UNIQUE NOT NULL CHECK (REGEXP_LIKE(IC,'[0-9]{8,10}')),
    DIC VARCHAR(12) UNIQUE NOT NULL CHECK (REGEXP_LIKE(DIC,'[A-Z]{2}[0-9]{8,10}'))
);

CREATE TABLE Vehicles (
    VIN VARCHAR(17) PRIMARY KEY,
    customer_ID NUMBER NOT NULL,
    FOREIGN KEY (customer_ID) REFERENCES Customers(ID),
    customer_tag VARCHAR(50)
);

CREATE TABLE Workplace (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ VARCHAR(100) NOT NULL --workplace_name
);

CREATE TABLE Employees (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    workplace_ID NUMBER,
    FOREIGN KEY (workplace_ID) REFERENCES Workplace(ID)
);

CREATE TABLE Orders (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_ VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    expected_finish_date DATE,
    price NUMERIC,
    billable_time INT, --sekundy
    description_ VARCHAR(500),
    vehicle_ID VARCHAR(17),
    customer_ID INT,
    technician_ID INT,
    FOREIGN KEY (vehicle_ID) REFERENCES Vehicles(VIN),
    FOREIGN KEY (customer_ID) REFERENCES Customers(ID),
    FOREIGN KEY (technician_ID) REFERENCES Employees(ID)
);

CREATE TABLE Calendar_Items (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ID INT,
    FOREIGN KEY (order_ID) REFERENCES Orders(ID),
    date_ DATE NOT NULL, --calendar_date
    start_time_ TIMESTAMP NOT NULL, --calendar_start
    end_time_ TIMESTAMP NOT NULL, --calendar_end
    is_assigned NUMBER(1) DEFAULT 0,
    type_ VARCHAR(50), --calendar_type
    created_by_ID INT,
    FOREIGN KEY (created_by_ID) REFERENCES Employees(ID),
    assigned_by_ID INT,
    --1) assigned_by_ID spravit (0,1) ale potom neobsahuje ID mozno takto
    --assigned_by_type INT CHECK (assigned_by_type IN (0,1)),
    --CHECK(
    --  (assigned_by_type = 0 AND assigned_by_ID IN (SELECT ID FROM Customers)) OR
    --  (assigned_by_type = 1 AND assigned_by_ID IN (SELECT ID FROM Employees))
    --)
    workplace_ID INT,
    mechanic_ID INT,
    FOREIGN KEY (workplace_ID) REFERENCES Workplace(ID),
    FOREIGN KEY (mechanic_ID) REFERENCES Employees(ID)
);

CREATE TABLE Services (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price NUMERIC NOT NULL,
    expected_time INT, --SEKUNDY
    needed_specialisation VARCHAR(50) NOT NULL,
    type_ INT CHECK (type_ IN (0,1)) --service_type
);

CREATE TABLE Store_Items (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_address VARCHAR(255) NOT NULL,
    name_ VARCHAR(100) NOT NULL, --item_name
    quantity INT NOT NULL,
    price NUMERIC NOT NULL
);


CREATE TABLE Technician (
    ID INT PRIMARY KEY REFERENCES Employees(ID),
    work_focus INT CHECK (work_focus IN (0,1))
);

CREATE TABLE Mechanic (
    ID INT PRIMARY KEY REFERENCES Employees(ID)
    -- mozne prepojenie mechanic->training_program?
    -- ze treningovy program bude mat <fk> id mechanika (cize employees) 
);

CREATE TABLE Manager (
    ID INT PRIMARY KEY REFERENCES Employees(ID)
);

CREATE TABLE Training_Programs (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- treba nejake inserty porobit
INSERT INTO Customers (email, phone_number) VALUES ('john.doe@example.com', '123456789');
INSERT INTO Customers (email, phone_number) VALUES ('company@example.com', '987654321');

INSERT INTO Individuals (ID, first_name, last_name) VALUES (1, 'John', 'Doe');

INSERT INTO Companies (ID, IC, DIC) VALUES (2, '12345678', 'SK1234567890');

INSERT INTO Vehicles (VIN, customer_ID, customer_tag) VALUES ('1HGCM82633A123456', 1, 'Osobné auto');
INSERT INTO Vehicles (VIN, customer_ID, customer_tag) VALUES ('2HGCM82633A654321', 2, 'Firemné vozidlo');

INSERT INTO Workplace (name_) VALUES ('Autoservis Bratislava');
INSERT INTO Workplace (name_) VALUES ('Autoservis Košice');


INSERT INTO Employees (first_name, last_name, email, phone_number, workplace_ID) VALUES
('Peter', 'Novák', 'peter.novak@example.com', '0911123456', 1);
INSERT INTO Employees (first_name, last_name, email, phone_number, workplace_ID) VALUES 
('Jana', 'Horváthová', 'jana.horvath@example.com', '0911987654', 2);

INSERT INTO Orders (state_, start_date, expected_finish_date, price, billable_time, description_, vehicle_ID, customer_ID, technician_ID) VALUES
('Prijatá', TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-03-05', 'YYYY-MM-DD'), 500.00, 14400, 'Výmena bŕzd', '1HGCM82633A123456', 1, 1);
INSERT INTO Orders (state_, start_date, expected_finish_date, price, billable_time, description_, vehicle_ID, customer_ID, technician_ID) VALUES
('Dokončená', TO_DATE('2024-02-20', 'YYYY-MM-DD'), TO_DATE('2024-02-25', 'YYYY-MM-DD'), 300.00, 10800, 'Servis klimatizácie', '2HGCM82633A654321', 2, 2);

INSERT INTO Calendar_Items (order_ID, date_, start_time_, end_time_, is_assigned, type_, created_by_ID, assigned_by_ID, workplace_ID, mechanic_ID) VALUES 
(1, TO_DATE('2024-03-02', 'YYYY-MM-DD'), TO_TIMESTAMP('2024-03-02 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-03-02 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 'Práca na brzdách', 1, 2, 1, 1);
INSERT INTO Calendar_Items (order_ID, date_, start_time_, end_time_, is_assigned, type_, created_by_ID, assigned_by_ID, workplace_ID, mechanic_ID) VALUES 
(2, TO_DATE('2024-02-21', 'YYYY-MM-DD'), TO_TIMESTAMP('2024-02-21 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-21 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 'Servis klímy', 2, 1, 2, 2);

INSERT INTO Services (price, expected_time, needed_specialisation, type_) VALUES (100.00, 7200, 'Brzdový systém', 0);
INSERT INTO Services (price, expected_time, needed_specialisation, type_) VALUES (80.00, 5400, 'Klimatizácia', 1);

INSERT INTO Store_Items (store_address, name_, quantity, price) VALUES ('Bratislava, Hlavná 1', 'Brzdové doštičky', 50, 25.00);
INSERT INTO Store_Items (store_address, name_, quantity, price) VALUES ('Košice, Štefánikova 10', 'Chladiaci plyn', 30, 15.00);

INSERT INTO Technician (ID, work_focus) VALUES (1, 0);
INSERT INTO Technician (ID, work_focus) VALUES (2, 1);

INSERT INTO Mechanic (ID) VALUES (1);
INSERT INTO Mechanic (ID) VALUES (2);

INSERT INTO Manager (ID) VALUES (1);

INSERT INTO Training_Programs (name) VALUES ('Certifikát na opravu bŕzd');
INSERT INTO Training_Programs (name) VALUES ('Kurz diagnostiky motorov');

SELECT * FROM Customers;
COMMIT;