-- Task 07: Autoopravovna
-- xborda01, xhasto00

-- ER diagram Updates: 
--  Switched cardinality on relationship 'done at' between 'Calendar items' and 'Workplace'
--  Removed '<<FK>> assigned_by_ID' from 'Calendar items' table  
--  Added 'variable_symbol' to 'Individuals' table

-- Table Services_on_order implements N to M relationship between Services and Orders tables
-- Table Items_on_order implements N to M relationship between Store_Items and Orders tables
-- Table Mechanic_Has_Program implements N to M relationship between Mechanic and Training_Programs tables

DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE Individuals CASCADE CONSTRAINTS;
DROP TABLE Companies CASCADE CONSTRAINTS;
DROP TABLE Vehicles CASCADE CONSTRAINTS;
DROP TABLE Workplace CASCADE CONSTRAINTS;
DROP TABLE Employees CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Calendar_Items CASCADE CONSTRAINTS;
DROP TABLE Services CASCADE CONSTRAINTS;
DROP TABLE Store_Items CASCADE CONSTRAINTS;
DROP TABLE Technician CASCADE CONSTRAINTS;
DROP TABLE Mechanic CASCADE CONSTRAINTS;
DROP TABLE Manager CASCADE CONSTRAINTS;
DROP TABLE Training_Programs CASCADE CONSTRAINTS;
DROP TABLE Services_on_order CASCADE CONSTRAINTS;
DROP TABLE Items_on_order CASCADE CONSTRAINTS;
DROP TABLE Mechanic_Has_Program CASCADE CONSTRAINTS;
DROP SEQUENCE Var_Symbol;

-- Generalization/Specialization - Customers, Individuals, Companies
-- Implemented by adding foreign key into Individuals/Companies table
-- that references customer in Customers table
CREATE TABLE Customers (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL
);

CREATE SEQUENCE Var_Symbol
START WITH 1000000
MAXVALUE 9999999
NOCYCLE;

CREATE TABLE Individuals (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Variable_symbol INT DEFAULT Var_Symbol.NEXTVAL,
    Customer_id INT NOT NULL,
    CONSTRAINT individuals_customer
		FOREIGN KEY (Customer_id) REFERENCES Customers (ID)
		ON DELETE CASCADE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE Companies (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Customer_id INT NOT NULL,
    CONSTRAINT companies_customer
		FOREIGN KEY (Customer_id) REFERENCES Customers (ID)
		ON DELETE CASCADE,
    IC VARCHAR(10) UNIQUE NOT NULL CHECK (REGEXP_LIKE(IC,'[0-9]{8}')),
    DIC VARCHAR(12) UNIQUE NOT NULL CHECK (REGEXP_LIKE(DIC,'[A-Z]{2}[0-9]{9,10}'))
);

CREATE TABLE Vehicles (
    VIN VARCHAR(17) PRIMARY KEY,
    customer_ID NUMBER NOT NULL,
    FOREIGN KEY (customer_ID) REFERENCES Customers(ID),
    customer_tag VARCHAR(50)
);

CREATE TABLE Workplace (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL 
);

-- Generalization/Specialization - Employees, Technician, Manager
-- Implemented by adding foreign key into Technician/Manager/Mechanic table
-- that references employee in Employees table
CREATE TABLE Employees (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    workplace_ID NUMBER,
    FOREIGN KEY (workplace_ID) REFERENCES Workplace(ID)
);

CREATE TABLE Orders (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "state" INT NOT NULL,
    start_date DATE NOT NULL,
    expected_finish_date DATE,
    price INT,
    billable_time INT,
    "description" VARCHAR(100),
    vehicle_ID VARCHAR(17),
    customer_ID INT,
    technician_ID INT,
    FOREIGN KEY (vehicle_ID) REFERENCES Vehicles(VIN),
    FOREIGN KEY (customer_ID) REFERENCES Customers(ID),
    FOREIGN KEY (technician_ID) REFERENCES Employees(ID)
);

CREATE TABLE Calendar_Items (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ID INT,
    FOREIGN KEY (order_ID) REFERENCES Orders(ID),
    "date" DATE NOT NULL, 
    "start_time" TIMESTAMP NOT NULL, 
    "end_time" TIMESTAMP NOT NULL, 
    is_assigned INT DEFAULT 0,
    "type" INT NOT NULL, 
    created_by_ID INT,
    FOREIGN KEY (created_by_ID) REFERENCES Employees(ID),
    workplace_ID INT,
    FOREIGN KEY (workplace_ID) REFERENCES Workplace(ID),
    mechanic_ID INT,
    FOREIGN KEY (mechanic_ID) REFERENCES Employees(ID)
);

CREATE TABLE Services (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price INT NOT NULL,
    expected_time INT NOT NULL,
    needed_specialisation VARCHAR(50) NOT NULL,
    "type" INT CHECK ("type" IN (0,1)) 
);

CREATE TABLE Services_on_order(
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES Orders (ID),
    service_id INT NOT NULL,
    FOREIGN KEY (service_id) REFERENCES Services (ID)
);

CREATE TABLE Store_Items (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_address VARCHAR(10) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    price INT NOT NULL
);

CREATE TABLE Items_on_order(
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES Orders (ID),
    item_id INT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES Store_Items (ID)
);

CREATE TABLE Technician (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Employee_id INT NOT NULL,
    CONSTRAINT technician_employees
		FOREIGN KEY (Employee_id) REFERENCES Employees (ID)
		ON DELETE CASCADE,
    work_focus INT CHECK (work_focus IN (0,1))
);

CREATE TABLE Training_Programs (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL
);

CREATE TABLE Mechanic (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Employee_id INT NOT NULL,
    CONSTRAINT mechanic_employees
		FOREIGN KEY (Employee_id) REFERENCES Employees (ID)
		ON DELETE CASCADE
);

CREATE TABLE Mechanic_Has_Program(
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id INT NOT NULL,
    FOREIGN KEY (program_id) REFERENCES Training_Programs (ID),
    mechanic_id INT NOT NULL,
    FOREIGN KEY (mechanic_id) REFERENCES Mechanic (ID)
);

CREATE TABLE Manager (
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Employee_id INT NOT NULL,
    CONSTRAINT manager_employees
		FOREIGN KEY (Employee_id) REFERENCES Employees (ID)
		ON DELETE CASCADE
);

-- Insert example data
INSERT INTO Customers (email, phone_number) VALUES ('john.doe@example.com', '123456789');
INSERT INTO Customers (email, phone_number) VALUES ('company@example.com', '987654321');
INSERT INTO Customers (email, phone_number) VALUES ('mike.doe@example.com', '123456779');

INSERT INTO Individuals (Customer_id, first_name, last_name) VALUES (1, 'John', 'Doe');
INSERT INTO Individuals (Customer_id, first_name, last_name) VALUES (3, 'Mike', 'Doe');

INSERT INTO Companies (Customer_id, IC, DIC) VALUES (2, '12345678', 'SK1234567890');

INSERT INTO Vehicles (VIN, customer_ID, customer_tag) VALUES ('1HGCM82633A123456', 1, 'Osobné auto');
INSERT INTO Vehicles (VIN, customer_ID, customer_tag) VALUES ('2HGCM82633A654321', 2, 'Firemné vozidlo 1');
INSERT INTO Vehicles (VIN, customer_ID, customer_tag) VALUES ('48H1M82633A654123', 2, 'Firemné vozidlo 2');

INSERT INTO Workplace ("name") VALUES ('Brana 1');
INSERT INTO Workplace ("name") VALUES ('Brana 2');
INSERT INTO Workplace ("name") VALUES ('Kancelaria 1');


INSERT INTO Employees (first_name, last_name, email, phone_number, workplace_ID) VALUES
('Peter', 'Novák', 'peter.novak@example.com', '0911123456', 1);
INSERT INTO Employees (first_name, last_name, email, phone_number, workplace_ID) VALUES 
('Jana', 'Horváthová', 'jana.horvath@example.com', '0911987654', 2);
INSERT INTO Employees (first_name, last_name, email, phone_number, workplace_ID) VALUES
('Jozef', 'Sota', 'jozef.sota@example.com', '129406873', 3);

INSERT INTO Orders ("state", start_date, expected_finish_date, price, billable_time, "description", vehicle_ID, customer_ID, technician_ID) VALUES
(0, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-03-05', 'YYYY-MM-DD'), 500.00, 14400, 'Výmena bŕzd', '1HGCM82633A123456', 1, 1);

INSERT INTO Orders ("state", start_date, expected_finish_date, price, billable_time, "description", vehicle_ID, customer_ID, technician_ID) VALUES
(3, TO_DATE('2024-02-20', 'YYYY-MM-DD'), TO_DATE('2024-02-25', 'YYYY-MM-DD'), 300.00, 10800, 'Servis klimatizácie', '2HGCM82633A654321', 2, 2);
INSERT INTO Orders ("state", start_date, expected_finish_date, price, billable_time, "description", vehicle_ID, customer_ID, technician_ID) VALUES
(0, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-03-05', 'YYYY-MM-DD'), 400.00, 14400, 'Výmena bŕzd', '2HGCM82633A654321', 2, 1);
INSERT INTO Orders ("state", start_date, expected_finish_date, price, billable_time, "description", vehicle_ID, customer_ID, technician_ID) VALUES
(0, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-03-05', 'YYYY-MM-DD'), 450.00, 14400, 'Výmena bŕzd', '48H1M82633A654123', 2, 1);

INSERT INTO Calendar_Items (order_ID, "date", "start_time", "end_time", "type", created_by_ID, workplace_ID, mechanic_ID) VALUES 
(1, TO_DATE('2024-03-02', 'YYYY-MM-DD'), TO_TIMESTAMP('2024-03-02 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-03-02 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 1, 1, 2);
INSERT INTO Calendar_Items (order_ID, "date", "start_time", "end_time", "type", created_by_ID, workplace_ID, mechanic_ID) VALUES 
(2, TO_DATE('2024-02-21', 'YYYY-MM-DD'), TO_TIMESTAMP('2024-02-21 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-02-21 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1, 2, 2);
INSERT INTO Calendar_Items (order_ID, "date", "start_time", "end_time", "type", created_by_ID, workplace_ID, mechanic_ID) VALUES 
(1, TO_DATE('2024-03-03', 'YYYY-MM-DD'), TO_TIMESTAMP('2024-03-03 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-03-03 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 1, 1, 2);

INSERT INTO Services (price, expected_time, needed_specialisation, "type") VALUES (100.00, 7200, 'Brzdový systém', 0);
INSERT INTO Services (price, expected_time, needed_specialisation, "type") VALUES (80.00, 5400, 'Klimatizácia', 1);

INSERT INTO Store_Items (store_address, "name", quantity, price) VALUES ('A1', 'Brzdové doštičky', 50, 25.00);
INSERT INTO Store_Items (store_address, "name", quantity, price) VALUES ('B1', 'Chladiaci plyn', 30, 15.00);

INSERT INTO Technician (Employee_id, work_focus) VALUES (1, 0);
INSERT INTO Mechanic (Employee_id) VALUES (2);
INSERT INTO Manager (Employee_id) VALUES (3);

INSERT INTO Training_Programs ("name") VALUES ('Certifikát na opravu bŕzd');
INSERT INTO Training_Programs ("name") VALUES ('Kurz diagnostiky motorov');

INSERT INTO Mechanic_Has_Program (mechanic_id, program_id) VALUES (1,1);
INSERT INTO Mechanic_Has_Program (mechanic_id, program_id) VALUES (1,2);

INSERT INTO Items_on_order (item_id, order_id) VALUES (1,1);
INSERT INTO Items_on_order (item_id, order_id) VALUES (2,1);
INSERT INTO Items_on_order (item_id, order_id) VALUES (2,2);

INSERT INTO Services_on_order (service_id, order_id) VALUES (1,1);
INSERT INTO Services_on_order (service_id, order_id) VALUES (2,1);
INSERT INTO Services_on_order (service_id, order_id) VALUES (2,2);

-- 3. PART - SQL SELECTS --

-- Three queries that join 2 tables
    -- Get all vehicles for each customer
    SELECT Customers.email, Vehicles.VIN, Vehicles.customer_tag FROM Customers
    JOIN Vehicles ON Vehicles.customer_ID = Customers.ID;

    -- Get all orders with its description and assigned dates (ordered by order's ID)
    SELECT Orders.ID, Orders."description", Calendar_Items."date"
    FROM Orders 
    JOIN Calendar_Items ON Calendar_Items.order_ID = Orders.ID
    ORDER BY Orders.ID ASC;

    -- Get employees per workplace
    SELECT Workplace."name" AS "Workplace name", Employees.first_name, Employees.last_name 
    FROM Workplace 
    JOIN Employees ON Employees.workplace_ID = Workplace.ID
    ORDER BY Workplace.ID ASC;

-- One query that joins 3 tables
    -- Get all orders each with its assigned customer and technician 
    SELECT Orders.ID AS "Order", Customers.email AS "Customer email", Employees.email AS "Employee email" 
    FROM Orders 
    JOIN Customers ON Customers.ID = Orders.customer_ID
    JOIN Employees ON Employees.ID = Orders.technician_ID;
    
-- Three queries with GROUP BY clause and aggregation function
    -- Get count of orders processed by each technician
    SELECT COUNT(ID) AS "Count of orders", Technician_ID FROM Orders GROUP BY Technician_ID;

    -- Get average price per type
    SELECT AVG(price) AS "Average price", "type" AS "Service type" FROM Services GROUP BY "type";

    -- Get total price of orders for customer per vehicle 
    SELECT SUM(price) AS "Total price", customer_ID, vehicle_ID AS "Vehicle VIN" FROM Orders 
    WHERE Orders.customer_ID = 2 -- company ID
    GROUP BY customer_ID, vehicle_ID;

-- One query with predicate EXISTS
    -- Get calendar items that are not assigned yet 
    SELECT * FROM Calendar_Items 
    WHERE EXISTS (SELECT ID FROM Technician WHERE Technician.ID = Calendar_Items.created_by_ID AND Calendar_Items.is_assigned = 0);

-- Two queries with predicate IN with nested SELECT
    -- Get employees who are mechanics (show personal details about mechanics) 
    SELECT * FROM Employees 
    WHERE ID IN (SELECT Employee_id FROM Mechanic);

    -- Get all customers who are individuals
    SELECT * FROM Customers
    WHERE ID IN (SELECT Customer_id FROM Individuals);

COMMIT;